// lib/zipCentroids.ts
//
// Offline US ZIP → centroid lookup for distance-aware buyer routing.
//
// WHY OFFLINE (not lib/geocode.ts): matching/suggest runs on the money path
// for every qualified buyer. lib/geocode.ts hits zippopotam.us / Nominatim
// over the network — fine ONCE per rancher at signup, a latency + rate-limit
// failure mode on every buyer during a demand spike. So buyers resolve from a
// static vendored table (lib/zipCentroids.data.ts, regenerated by
// tools/generate-zip-centroids.mjs) with zero network calls.
//
// The table is parsed LAZILY into a Map on first lookup — a buyer with no ZIP
// (every consumer row as of 2026-07-22) never pays the ~40 ms parse.

import { ZIP_CENTROID_TABLE } from './zipCentroids.data';
import { normalizeState } from './states';
import { normalizeZip } from './zipFormat';

// Re-exported for convenience — but callers that ONLY need to normalize a ZIP
// should import from './zipFormat' directly so they don't pull the 1 MB table
// into their bundle (the funnel signup route does exactly that).
export { normalizeZip };

export interface ZipCentroid {
  zip: string;
  lat: number;
  lng: number;
  /** 2-letter state code the USPS assigns this ZIP. */
  state: string;
}

let table: Map<string, ZipCentroid> | null = null;

function getTable(): Map<string, ZipCentroid> {
  if (table) return table;
  const m = new Map<string, ZipCentroid>();
  for (const line of ZIP_CENTROID_TABLE.split('\n')) {
    if (!line) continue;
    const [zip, lat, lng, state] = line.split(',');
    if (!zip || !state) continue;
    const la = Number(lat);
    const ln = Number(lng);
    if (!Number.isFinite(la) || !Number.isFinite(ln)) continue;
    m.set(zip, { zip, lat: la, lng: ln, state });
  }
  table = m;
  return m;
}

/** Centroid for a US ZIP, or null when the ZIP is malformed or unknown. */
export function lookupZipCentroid(raw: unknown): ZipCentroid | null {
  const zip = normalizeZip(raw);
  if (!zip) return null;
  return getTable().get(zip) || null;
}

/**
 * Centroid for a buyer's ZIP, CROSS-CHECKED against the state we route on.
 *
 * Routing eligibility is decided by the buyer's `State` field; the ZIP is only
 * ever a precision refinement on top of it. A ZIP that belongs to a different
 * state is therefore a typo (or a work/parents' address) — trusting it would
 * measure miles from a place the buyer isn't, and could hand a delivery-only
 * rancher a bogus "within radius" verdict. Mismatch ⇒ null ⇒ the caller falls
 * back to the state-hop sort, exactly as if no ZIP were present.
 */
export function resolveBuyerCentroid(zip: unknown, state: unknown): ZipCentroid | null {
  const hit = lookupZipCentroid(zip);
  if (!hit) return null;
  const want = normalizeState(state);
  if (!want) return null;
  return hit.state === want ? hit : null;
}
