// app/api/cron/synthetic-e2e/route.ts
//
// SYNTHETIC E2E SMOKE — daily probe through the full buyer funnel.
//
// Why: a healthy build can pass typecheck, deploy successfully, and STILL be
// broken at runtime (wrong env var, missing rancher in test state, JWT mint
// throwing, matching/suggest 500ing). The deploy-drift cron catches stale
// builds; this cron catches WORKING-but-broken builds.
//
// Procedure (every action returns ok/error; chain stops on first failure):
//   1. POST /api/consumers with synthetic buyer in MT (has live rancher Foodstead)
//      + REQUIRED phone (validates phone gate fires)
//   2. Verify response.qualifyUrl is present (validates auto-route bypass plug)
//   3. Extract token from qualifyUrl, POST /api/qualify with passing quiz answers
//   4. Verify response.qualified=true + referralId returned (validates matching)
//   5. Find the Referral in Airtable, verify Status='Intro Sent'
//   6. CLEANUP: mark synthetic Consumer + Referral as test data (Notes prefix)
//      so they don't pollute analytics or fire real ranchers
//
// Schedule: daily 6am UTC. Fires Telegram on any failure with the failed step.
// One green ping per day on success (so silence = real broken).

import { NextResponse } from 'next/server';
import { getRecordById, deleteRecord, TABLES } from '@/lib/airtable';
import { decrementCapacity, syncCapacityToAirtable } from '@/lib/rancherCapacity';
import { sendTelegramMessage, TELEGRAM_ADMIN_CHAT_ID } from '@/lib/telegram';
import { withCronRun } from '@/lib/cronRun';

export const maxDuration = 120;

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://buyhalfcow.com';

interface E2EResult {
  status: 'success' | 'partial' | 'error';
  recordsTouched: number;
  notes: string;
}

interface StepFailure {
  step: string;
  error: string;
  detail?: any;
}

async function realHandler(_request: Request): Promise<E2EResult> {
  // Unique synthetic email per run — never collides with real signups.
  // Domain reserved.invalid is RFC 6761 — guaranteed never to resolve, so
  // emails to it never actually fire even if a code path tries to send.
  const runId = `e2e-${Date.now()}`;
  const syntheticEmail = `${runId}@e2e.reserved.invalid`;
  const syntheticPhone = '+15555550100';
  const syntheticState = 'MT'; // Foodstead Beef is operational here

  let failure: StepFailure | null = null;
  let consumerId: string | null = null;
  let referralId: string | null = null;
  let qualifyToken: string | null = null;

  // STEP 1: signup
  try {
    const r = await fetch(`${SITE_URL}/api/consumers`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        fullName: `E2E Synthetic Test ${runId}`,
        email: syntheticEmail,
        phone: syntheticPhone,
        state: syntheticState,
        orderType: 'Half',
        budgetRange: '$2000-$2500',
        timing: 'Within 30 days',
        interestBeef: true,
        intentScore: 95,
        intentClassification: 'High',
        source: 'synthetic-e2e-cron',
        notes: 'SYNTHETIC E2E TEST — auto-generated by cron. Do not contact.',
      }),
    });
    const j = await r.json().catch(() => ({}));
    if (!r.ok) {
      failure = { step: 'POST /api/consumers', error: `HTTP ${r.status}`, detail: j };
    } else if (!j?.consumer?.id) {
      failure = { step: 'POST /api/consumers', error: 'no consumer id in response', detail: j };
    } else if (!j?.qualifyUrl) {
      failure = { step: 'qualifyUrl absent', error: 'response missing qualifyUrl — bypass plug regressed', detail: j };
    } else {
      consumerId = j.consumer.id;
      const u = new URL(j.qualifyUrl);
      qualifyToken = u.searchParams.get('token');
      if (!qualifyToken) {
        failure = { step: 'qualifyUrl token extract', error: 'no token in URL' };
      }
    }
  } catch (e: any) {
    failure = { step: 'POST /api/consumers (network)', error: e?.message || 'unknown' };
  }

  // STEP 2: complete quiz (only if signup succeeded)
  if (!failure && consumerId && qualifyToken) {
    try {
      const r = await fetch(`${SITE_URL}/api/qualify`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          token: qualifyToken,
          consumerId,
          answers: {
            tier: 'Half',
            timing: 'Within 30 days',
            storage: 'have_freezer',
            ack: true,
          },
        }),
      });
      const j = await r.json().catch(() => ({}));
      if (!r.ok) {
        failure = { step: 'POST /api/qualify', error: `HTTP ${r.status}`, detail: j };
      } else if (!j?.qualified) {
        failure = { step: 'qualify score gate', error: `quiz failed score gate (score=${j?.score})`, detail: j };
      } else {
        referralId = j.referralId || null;
        if (!referralId) {
          failure = { step: 'matching/suggest fire', error: 'qualified but no referralId — matching did not fire', detail: j };
        }
      }
    } catch (e: any) {
      failure = { step: 'POST /api/qualify (network)', error: e?.message || 'unknown' };
    }
  }

  // STEP 3: verify referral landed in Airtable w/ Intro Sent
  if (!failure && referralId) {
    try {
      const ref: any = await getRecordById(TABLES.REFERRALS, referralId);
      const status = String(ref?.['Status'] || '');
      if (status !== 'Intro Sent') {
        failure = {
          step: 'Referral status check',
          error: `Referral status='${status}' expected 'Intro Sent'`,
          detail: { referralId, status, rancher: ref?.['Suggested Rancher Name'] },
        };
      }
    } catch (e: any) {
      failure = { step: 'getRecordById Referral', error: e?.message || 'unknown' };
    }
  }

  // CLEANUP (SYN-1 2026-06-05): hard-delete instead of just flag. Prior
  // updateRecord(Status='Closed Lost') skipped the proper close path so
  // the rancher's capacity INCR from matching/suggest was never DECR'd —
  // synthetic runs silently drifted cap counters every day. New flow:
  //   1. DECR the matched rancher's capacity counter atomically (Redis +
  //      Airtable mirror sync). Mirrors what /api/referrals/[id] PATCH does
  //      on Closed Lost.
  //   2. DELETE the Referral row (no debris in admin/referrals UI).
  //   3. DELETE the Consumer row (no debris in admin/funnel + no false
  //      "qualified buyer not matched" signals on dashboards).
  let cleaned = 0;
  if (referralId) {
    try {
      // Pull rancher id off the referral so we can DECR the right counter.
      const ref: any = await getRecordById(TABLES.REFERRALS, referralId);
      const rancherIds: string[] =
        (ref?.['Rancher'] as string[]) ||
        (ref?.['Suggested Rancher'] as string[]) ||
        [];
      const rancherId = rancherIds[0];
      if (rancherId) {
        try {
          const newCount = await decrementCapacity(rancherId);
          await syncCapacityToAirtable(rancherId, newCount);
        } catch (e: any) {
          console.warn(`[synthetic-e2e cleanup] DECR failed for rancher ${rancherId}:`, e?.message);
        }
      }
      await deleteRecord(TABLES.REFERRALS, referralId);
      cleaned++;
    } catch (e: any) {
      console.warn('[synthetic-e2e cleanup] referral delete failed:', e?.message);
    }
  }
  if (consumerId) {
    try {
      await deleteRecord(TABLES.CONSUMERS, consumerId);
      cleaned++;
    } catch (e: any) {
      console.warn('[synthetic-e2e cleanup] consumer delete failed:', e?.message);
    }
  }

  // Report
  if (failure) {
    try {
      await sendTelegramMessage(
        TELEGRAM_ADMIN_CHAT_ID,
        `🚨 <b>SYNTHETIC E2E FAILED</b>\n\n` +
          `Step: <b>${failure.step}</b>\n` +
          `Error: <code>${failure.error}</code>\n\n` +
          (failure.detail ? `Detail: <code>${JSON.stringify(failure.detail).slice(0, 300)}</code>\n\n` : '') +
          `<i>Funnel broken — investigate before more leads arrive. Run ID: ${runId}</i>`,
      );
    } catch {}
    return {
      status: 'error',
      recordsTouched: cleaned,
      notes: `E2E broken at: ${failure.step} — ${failure.error}`,
    };
  }

  try {
    await sendTelegramMessage(
      TELEGRAM_ADMIN_CHAT_ID,
      `✅ <b>SYNTHETIC E2E PASSED</b>\n\n` +
        `Signup → qualify → match → Intro Sent all green.\n` +
        `Consumer: <code>${consumerId}</code>\n` +
        `Referral: <code>${referralId}</code>\n\n` +
        `<i>Run ID: ${runId}</i>`,
    );
  } catch {}

  return {
    status: 'success',
    recordsTouched: cleaned,
    notes: `passed (cleaned ${cleaned} records)`,
  };
}

async function authedHandler(request: Request): Promise<Response> {
  const cronSecret = process.env.CRON_SECRET;
  if (cronSecret) {
    const authHeader = request.headers.get('authorization');
    const ok = authHeader === `Bearer ${cronSecret}`;
    if (!ok) {
      const { searchParams } = new URL(request.url);
      if (searchParams.get('secret') !== cronSecret) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
      }
    }
  }
  return withCronRun('synthetic-e2e', realHandler)(request);
}

export const GET = authedHandler;
export const POST = authedHandler;
